use js(BOTH) instead of js(IR)
This allows using korio, which is not yet compatible with the IR compiler.

Tests now compile and run although they fail with

Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is
called; if returning a Promise, ensure it resolves.
(...hasura-subset-jsLegacy-test/adapter-nodejs.js)